"""Built-in Code Generation Agent."""

from __future__ import annotations

import asyncio
import textwrap
from typing import Any

from neuralforge.agents.base import AgentCapability, BaseAgent
from neuralforge.core.context import PipelineContext


class CoderAgent(BaseAgent):
    """Agent that generates code based on specifications.

    Config:
        task: Description of what code to generate.
        language: Target programming language (default "python").
        style: Code style hint ("functional", "oop", "minimal").
        constraints: List of constraints/requirements.
    """

    @property
    def name(self) -> str:
        return "coder"

    @property
    def capabilities(self) -> list[AgentCapability]:
        return [AgentCapability.CODE_GENERATION, AgentCapability.TEXT_GENERATION]

    @property
    def description(self) -> str:
        return "Generates code from natural language specifications."

    def validate_config(self, config: dict[str, Any]) -> list[str]:
        errors = []
        if "task" not in config:
            errors.append("Missing required config key: 'task'")
        return errors

    async def execute(
        self,
        config: dict[str, Any],
        dependencies: dict[str, Any],
        context: PipelineContext,
    ) -> dict[str, Any]:
        task = config["task"]
        language = config.get("language", "python")
        style = config.get("style", "functional")
        constraints = config.get("constraints", [])

        # Enrich task with dependency context
        if dependencies:
            dep_summary = self._summarize_dependencies(dependencies)
            task = f"{task}\n\nContext from upstream:\n{dep_summary}"

        # Simulate code generation (replace with real LLM call)
        await asyncio.sleep(0.05)
        code = self._generate_stub(task, language, style)

        return {
            "task": task,
            "language": language,
            "style": style,
            "code": code,
            "lines": len(code.splitlines()),
            "constraints_met": len(constraints),
        }

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    @staticmethod
    def _summarize_dependencies(deps: dict[str, Any]) -> str:
        """Create a concise summary of upstream results."""
        lines = []
        for name, result in deps.items():
            if isinstance(result, dict):
                if "count" in result:
                    lines.append(f"- {name}: {result['count']} items")
                if "query" in result:
                    lines.append(f"- {name} query: {result['query']}")
                if "code" in result:
                    lines.append(f"- {name}: generated {result.get('lines', '?')} lines")
            else:
                lines.append(f"- {name}: {str(result)[:100]}")
        return "\n".join(lines)

    @staticmethod
    def _generate_stub(task: str, language: str, style: str) -> str:
        """Generate placeholder code. Override with real LLM integration."""
        if language == "python":
            return textwrap.dedent(f'''\
                """Auto-generated by NeuralForge CoderAgent."""

                from typing import Any


                def solve() -> dict[str, Any]:
                    """Solve: {task[:60]}..."""
                    # TODO: Implement {style} solution
                    return {{"status": "generated", "language": "{language}"}}


                if __name__ == "__main__":
                    result = solve()
                    print(result)
            ''')
        if language == "javascript":
            return textwrap.dedent(f'''\
                // Auto-generated by NeuralForge CoderAgent

                function solve() {{
                    // TODO: Implement {style} solution
                    // Task: {task[:60]}...
                    return {{ status: "generated", language: "{language}" }};
                }}

                module.exports = {{ solve }};
            ''')
        return f"// Auto-generated: {task[:80]}\n// Language: {language}, Style: {style}"
